# --- MySQL Settings (Aiven Online) ---
spring.datasource.url=jdbc:mysql://chat-apprealtime-nganvuonglebao-db8a.d.aivencloud.com:26368/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_6Nf-0qUCBDXibAJAyxH
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Hibernate Settings ---
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- Initialization Settings ---
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=VARCHAR

